spring:
  application:
    name: candle-service
  datasource:
    url: jdbc:postgresql://localhost:5432/candle_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        schema:
          enum:
            check_constraints: false   #prevents enum CHECK creation
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus